install:
  - pip install --use-mirrors conda

  - conda install numpy
  - conda install scipy
  - conda install matplotlib
  - conda install pillow
  - conda install cython
  - conda install six
  - conda install nose

before_build:
  - python setup.py build_ext --inplace

before_test:
  - nosetests --exe -v --with-doctest skimage
